### ISSUE TITLE
Missing Mainnet Registration Address on Documentation

### ISSUE THREAD

**Issue by WenmergeDev** [Layr-Labs/eigenlayer-docs#101]
Hi,

I was trying to go through the docs to see how can I setup the operator. And found that in [https://docs.eigenlayer.xyz/eigenlayer/operator-guides/operator-installation#registration](https://docs.eigenlayer.xyz/eigenlayer/operator-guides/operator-installation#registration), only Goerli Smart contract addresses is listed.

Is this guide outdated or am I looking at the wrong spot to see how we can operate a node ?

Thanks :)

**Comment by bxmmm1** [comment]
@shrimalmadhur

**Comment by wesfloyd** [comment]
Can you clarify which line of docs you're referring to?

https://github.com/Layr-Labs/eigenlayer-docs/blob/main/docs/eigenlayer/operator-guides/operator-installation.md?plain=1

**Comment by bxmmm1** [comment]
In my case, https://github.com/Layr-Labs/eigenlayer-docs/blob/a957e43ac282db5af70ffe648bc1a8e28d087e07/docs/eigenda/networks/mainnet.md?plain=1#L6

**Comment by wesfloyd** [comment]
@bxmmm1 this issue was raised for " docs to see how can I setup the operator". The link you shared is for EigenDA Rollup developers (different user type).

Let's close this for now, b/c the original issue the ticket was opened for is resolved in the latest version of the Operator CLI.
