### ISSUE TITLE
Add github in #JOIN_THE_COMMUNITY_SECTION on eigenlayer website 

### ISSUE THREAD

**Issue by wnhedaxx** [Layr-Labs/eigenlayer-docs#113]
Please add github on eigenlayer website https://www.eigenlayer.xyz/ 
![Uploading Screenshot_2024-02-25-15-45-50-384_com.android.chrome.jpg…]()

```[tasklist]
### Tasks
```

**Comment by Dexta15** [comment]
I don't think there's a need for that,
Since the GitHub link is on Discord,
But I'll inform moderators on Discord tho

**Comment by wnhedaxx** [comment]
GitHub link is on docs also, I thought it would be better and easy for website visitors to checkout your GitHub also...
Personally when i first visited eigenlayer website. I was looking for GitHub i didn't get anywhere then i searched on Google , then i got Google docs, and then i got eigenlayer GitHub profile...also layr labs organisation name seems phishing for me then i visited eigenlayer discord and then i got satisfied that i am in real eigenlayer GitHub.

**Comment by dabit3** [comment]
Thanks @wnhedaxx we've added additional community resources now [here](https://docs.eigenlayer.xyz/eigenlayer/resources/)
