### ISSUE TITLE
key-terms page not found

### ISSUE THREAD

**Issue by renlulu** [Layr-Labs/eigenlayer-docs#128]
Link from https://docs.eigenlayer.xyz/eigenlayer/overview has been broken.

![image](https://github.com/Layr-Labs/eigenlayer-docs/assets/8149051/46873f7c-17a6-46c9-bcf5-16206c74f201)

<img width="1062" alt="image" src="https://github.com/Layr-Labs/eigenlayer-docs/assets/8149051/9e9d8112-b2a3-481d-b039-12fb44bbfb49">

https://docs.eigenlayer.xyz/eigenlayer/key-terms

**Comment by zm-moon** [comment]
Just submitted a PR on this issue.
#157
