### ISSUE TITLE
Typo - "requirement for both for ZK and Optimistic rollups" has an extra "for"

### ISSUE THREAD

**Issue by flanagansteve** [Layr-Labs/eigenlayer-docs#46]
The phrase "requirement for both for ZK and Optimistic rollups" can be found in two places:

	modified:   docs/eigenda-guides/eigenda-overview.md
	modified:   docs/eigenda-guides/eigenda-rollup-user-guides/building-on-top-of-eigenda.md

and it should read  "requirement for both ZK and Optimistic rollups"  instead 😄 

I tried to open a PR to fix this, but it seems like i need extra permissions to do so

**Comment by JohnKraken** [comment]
Jups, the repo is not open. 
What also bothers me is that EigenDA is sometimes written as "EigenDA" and other times as "EigenDa".
