### ISSUE TITLE
Need Multilingual documentation 

### ISSUE THREAD

**Issue by Speedevs** [Layr-Labs/eigenlayer-docs#88]
This project's documentation is currently available in English.
We need more Language support like a button or a list to select the languages we want to set it to and read it .

**Comment by Dexta15** [comment]
Sorry to ask, is it hard to read it in English?

**Comment by Speedevs** [comment]
Not everyone can understand English fluently?.
People from Spain? German,Chinese .

Can't understand

**Comment by Speedevs** [comment]
You can't expect "Translator" since most times .
They translate it in very  bad way and not perfect.
Especially Chinese to English.

So I think it is needed / recommend it be done.

**Comment by Dexta15** [comment]
I understand your concern,
I will pass this info now.

**Comment by Speedevs** [comment]
Nice  appreciate

**Comment by dabit3** [comment]
Hi @Speedevs thanks for opening up the issue, we've addressed it [here](https://github.com/Layr-Labs/eigenlayer-docs/issues/112)
