### ISSUE TITLE
Faucet URL is not working

### ISSUE THREAD

**Issue by shivam-V8** [Layr-Labs/eigenlayer-docs#98]
Obtain Goerli ETH (aka goETH) via a Faucet is not working for the Option 1: [Paradigm Goerli Faucet](https://faucet.paradigm.xyz/)
Either to remove this or update it some other faucet provider URL

**Comment by Dexta15** [comment]
You can as well try 
Alchemy Faucet
Quicknode faucet
Coinbase faucet 

Make sure you have 0.001 Eth on your wallet balance too,
That could also be the issue

**Comment by dabit3** [comment]
We've updated the docs with links to the Holesky faucet and Goerli is now deprecated, thanks for opening up this issue and flagging.
